name: Code coverage
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
        
      - name: Send Email with Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Newman Test Report
          to: ${{ secrets.SMTP_TO_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
          body: |
            Newman Test Report
            Please find the Newman test report attached.
